use luminar;
show tables;
select * from staff;
select fname,lname,age,phno from staff;
select * from staff limit 4;
select fname,lname,age,phno from staff limit 2;
select * from staff where age>22;
select fname,lname,age,phno from staff where age=21;
select fname,lname,age from staff where age<23;
select fname,lname,age,phno from staff where loc='chennai';
create view locview as select fname,lname,age,phno from staff where loc='chennai' and age>23;
select * from locview;
show tables;
create view chennaidata as select fname,lname,age,phno from staff where loc='chennai' and age=23;
select * from chennaidata;
select * from staff order by age;
select * from staff order by age desc;
select fname,lname,age,phno from staff order by age desc limit 2;
select fname,lname,age,phno from staff order by age  limit 1;
create view chenna as select fname,lname,age,phno from staff where loc='chennai' order by age desc limit 1;
select * from chenna;
select distinct * from staff;
select count(*) from staff;
select loc,count(*) from staff group by loc;
